// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: bff/proto/notification.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationRPCService_TransportMessage_FullMethodName = "/notification.NotificationRPCService/TransportMessage"
)

// NotificationRPCServiceClient is the client API for NotificationRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationRPCServiceClient interface {
	TransportMessage(ctx context.Context, in *NotificationMessageRequest, opts ...grpc.CallOption) (*NotificationMessageResponse, error)
}

type notificationRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationRPCServiceClient(cc grpc.ClientConnInterface) NotificationRPCServiceClient {
	return &notificationRPCServiceClient{cc}
}

func (c *notificationRPCServiceClient) TransportMessage(ctx context.Context, in *NotificationMessageRequest, opts ...grpc.CallOption) (*NotificationMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationMessageResponse)
	err := c.cc.Invoke(ctx, NotificationRPCService_TransportMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationRPCServiceServer is the server API for NotificationRPCService service.
// All implementations must embed UnimplementedNotificationRPCServiceServer
// for forward compatibility.
type NotificationRPCServiceServer interface {
	TransportMessage(context.Context, *NotificationMessageRequest) (*NotificationMessageResponse, error)
	mustEmbedUnimplementedNotificationRPCServiceServer()
}

// UnimplementedNotificationRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationRPCServiceServer struct{}

func (UnimplementedNotificationRPCServiceServer) TransportMessage(context.Context, *NotificationMessageRequest) (*NotificationMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransportMessage not implemented")
}
func (UnimplementedNotificationRPCServiceServer) mustEmbedUnimplementedNotificationRPCServiceServer() {
}
func (UnimplementedNotificationRPCServiceServer) testEmbeddedByValue() {}

// UnsafeNotificationRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationRPCServiceServer will
// result in compilation errors.
type UnsafeNotificationRPCServiceServer interface {
	mustEmbedUnimplementedNotificationRPCServiceServer()
}

func RegisterNotificationRPCServiceServer(s grpc.ServiceRegistrar, srv NotificationRPCServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationRPCService_ServiceDesc, srv)
}

func _NotificationRPCService_TransportMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationRPCServiceServer).TransportMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationRPCService_TransportMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationRPCServiceServer).TransportMessage(ctx, req.(*NotificationMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationRPCService_ServiceDesc is the grpc.ServiceDesc for NotificationRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationRPCService",
	HandlerType: (*NotificationRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransportMessage",
			Handler:    _NotificationRPCService_TransportMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bff/proto/notification.proto",
}
