// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: bff/proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMessageRequest) Reset() {
	*x = NotificationMessageRequest{}
	mi := &file_bff_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMessageRequest) ProtoMessage() {}

func (x *NotificationMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMessageRequest.ProtoReflect.Descriptor instead.
func (*NotificationMessageRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationMessageRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NotificationMessageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type NotificationMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Receiver      string                 `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMessageResponse) Reset() {
	*x = NotificationMessageResponse{}
	mi := &file_bff_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMessageResponse) ProtoMessage() {}

func (x *NotificationMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMessageResponse.ProtoReflect.Descriptor instead.
func (*NotificationMessageResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotificationMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationMessageResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NotificationMessageResponse) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

var File_bff_proto_notification_proto protoreflect.FileDescriptor

const file_bff_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x1cbff/proto/notification.proto\x12\fnotification\"f\n" +
	"\x1aNotificationMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\"\x81\x01\n" +
	"\x1bNotificationMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\tR\breceiver2\x83\x01\n" +
	"\x16NotificationRPCService\x12i\n" +
	"\x10TransportMessage\x12(.notification.NotificationMessageRequest\x1a).notification.NotificationMessageResponse\"\x00B\rZ\v./bff/protob\x06proto3"

var (
	file_bff_proto_notification_proto_rawDescOnce sync.Once
	file_bff_proto_notification_proto_rawDescData []byte
)

func file_bff_proto_notification_proto_rawDescGZIP() []byte {
	file_bff_proto_notification_proto_rawDescOnce.Do(func() {
		file_bff_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_proto_notification_proto_rawDesc), len(file_bff_proto_notification_proto_rawDesc)))
	})
	return file_bff_proto_notification_proto_rawDescData
}

var file_bff_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bff_proto_notification_proto_goTypes = []any{
	(*NotificationMessageRequest)(nil),  // 0: notification.NotificationMessageRequest
	(*NotificationMessageResponse)(nil), // 1: notification.NotificationMessageResponse
}
var file_bff_proto_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationRPCService.TransportMessage:input_type -> notification.NotificationMessageRequest
	1, // 1: notification.NotificationRPCService.TransportMessage:output_type -> notification.NotificationMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bff_proto_notification_proto_init() }
func file_bff_proto_notification_proto_init() {
	if File_bff_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_proto_notification_proto_rawDesc), len(file_bff_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_proto_notification_proto_goTypes,
		DependencyIndexes: file_bff_proto_notification_proto_depIdxs,
		MessageInfos:      file_bff_proto_notification_proto_msgTypes,
	}.Build()
	File_bff_proto_notification_proto = out.File
	file_bff_proto_notification_proto_goTypes = nil
	file_bff_proto_notification_proto_depIdxs = nil
}
